name: Deploy to GitHub Pages & Self-Hosted Server

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # --- 构建阶段（共享） ---
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_path: ${{ steps.upload_artifact.outputs.artifact_path }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run docs:build

      # 上传产物供后续 Jobs 使用
      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # --- 部署到 GitHub Pages ---
  deploy_to_github_pages:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # --- 部署到自有服务器 ---
  deploy_to_self_hosted:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: dist

      - name: Validate SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts  # 预存主机密钥
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "echo Connection Test"

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: "/app/src/document/"
          ARGS: "-avz --delete --rsync-path='mkdir -p /app/src/document && rsync'"

      - name: Verify Deployment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            ls -la /app/src/document
            df -h /app/src/document  # 检查挂载点
